project_id = "wipmfpcxquwrjszigwac"
[api]
enabled = true
[db]
major_version = 15
[realtime]
enabled = true
[auth]
enabled = true
[storage]
enabled = true
[edge_functions]
enabled = true
[functions.send-admin-email]
verify_jwt = false
[functions.admin-password-reset]
verify_jwt = false
[functions.admin-delete-user]
verify_jwt = false
